spring:
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017
      database: test

security:
  jwt:
    secret: a64bitSecretForJWTa64bitSecretForJWTa64bitSecretForJWTa64bit1234
    expiration: 360000